title:  Hi,Luke
name: overtrue
email: luke@kanheze.com
description: Luke，PHP工程师，从事web相关的开发工作。
keywords: luke的博客
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, Laravel, Git, Mac, RESTful, Stackoverflow, Sublime Text, OmniGaffale, OmniPlan]

timezone:    PRC
encoding: "utf-8"

url: http://kanheze.me
baseurl:  "/"
domain:    kanheze.me
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/myluke/myluke.github.io

# Build settings
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  # # # - jekyll-mentions
  # - jekyll-sitemap
  - jekyll-html-pipeline

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: https://github.com/myluke
    label: GitHub
    target: _blank

  -
    href: /about
    label: About


